VERSION=0.7.5
PACKAGE_NAME=Coflnet.Sky.Api.Client

docker run --rm -v "${PWD}:/local" --network host -u $(id -u ${USER}):$(id -g ${USER})  openapitools/openapi-generator-cli generate \
-i http://localhost:5005/api/swagger/v1/swagger.json \
-g csharp \
-o /local/out --additional-properties=packageName=$PACKAGE_NAME,packageVersion=$VERSION,licenseId=MIT,targetFramework=net8.0,library=restsharp

cd out
path=src/$PACKAGE_NAME/$PACKAGE_NAME.csproj
sed -i 's/GIT_USER_ID/Coflnet/g' $path
sed -i 's/GIT_REPO_ID/SkyApi/g' $path
sed -i 's/>OpenAPI/>Coflnet/g' $path
sed -i 's@annotations</Nullable>@annotations</Nullable>\n    <PackageReadmeFile>README.md</PackageReadmeFile>@g' $path
sed -i '34i    <None Include="../../../../README.md" Pack="true" PackagePath="\"/>' $path

# =============================================================================
# Post-generation patch: Fix Dictionary<string, string> filters query parameters
# =============================================================================
# The OpenAPI generator (csharp/restsharp) does not serialize Dictionary<string,
# string> parameters as individual query parameters. It generates empty blocks:
#
#     if (filters != null)
#     {
#     }
#
# This means any API endpoint using [FromQuery] Dictionary<string, string> will
# silently ignore all filter values, returning unfiltered results.
#
# The fix iterates over the dictionary entries and adds each key-value pair as
# a separate query parameter, which is how ASP.NET Core model-binds them:
#
#     if (filters != null)
#     {
#         foreach (var kvp in filters)
#         {
#             localVarRequestOptions.QueryParameters.Add(
#                 ClientUtils.ParameterToMultiMap("", kvp.Key, kvp.Value));
#         }
#     }
#
# This patch applies to ALL generated Api/*.cs files so any future endpoints
# using Dictionary filters are also covered.
# See: https://github.com/OpenAPITools/openapi-generator/issues/14encoding
# =============================================================================
echo "Patching empty Dictionary<string, string> filter blocks in generated API files..."
python3 - src/$PACKAGE_NAME/Api/*.cs <<'PYEOF'
import re, sys, glob

# Matches the empty filter block generated by openapi-generator for
# Dictionary<string, string> parameters. The generator emits:
#     if (filters != null)
#     {
#     }
# We replace it with a foreach that serializes each key-value pair as a
# separate query parameter (the way ASP.NET Core model-binds dictionaries).
EMPTY_BLOCK = re.compile(
    r'( +)if \(filters != null\)\n'
    r'\1\{\n'
    r'\1\}'
)

REPLACEMENT = (
    r'\1if (filters != null)\n'
    r'\1{\n'
    r'\1    foreach (var kvp in filters)\n'
    r'\1    {\n'
    r'\1        localVarRequestOptions.QueryParameters.Add(Coflnet.Sky.Api.Client.Client.ClientUtils.ParameterToMultiMap("", kvp.Key, kvp.Value));\n'
    r'\1    }\n'
    r'\1}'
)

total = 0
for pattern in sys.argv[1:]:
    for fname in glob.glob(pattern):
        with open(fname, 'r') as f:
            content = f.read()
        content_new, n = EMPTY_BLOCK.subn(REPLACEMENT, content)
        if n > 0:
            with open(fname, 'w') as f:
                f.write(content_new)
            print(f"  Patched {n} block(s) in {fname}")
            total += n
if total == 0:
    print("WARNING: No empty filter blocks found to patch!")
    sys.exit(1)
else:
    print(f"Patched {total} filter block(s) total.")
PYEOF

dotnet pack
cp src/$PACKAGE_NAME/bin/Release/$PACKAGE_NAME.*.nupkg ..
dotnet nuget push ../$PACKAGE_NAME.$VERSION.nupkg --api-key $NUGET_API_KEY --source "nuget.org" --skip-duplicate
rm *.sln